### ISSUE TITLE
Profiles not working

### ISSUE THREAD

**Issue by AndrejValand** [kolinger/skyrc-mc3000#4]
Used your installer and was not able to get the Profiles part of your solution working. when connected over BLE
![mc3000ble_mB1hQsAFYV](https://github.com/kolinger/skyrc-mc3000/assets/78184229/ec437239-9427-4332-bd90-d58ff8e39dbb)

But when i connect USB it reads slots i can name and assign preconfigured programs to slots. 
![image](https://github.com/kolinger/skyrc-mc3000/assets/78184229/d5c3a43c-1425-4c80-bdfa-d9354ed1923e)
![image](https://github.com/kolinger/skyrc-mc3000/assets/78184229/3a708be8-d5f8-4c16-8fe3-f9bf2bd6ab4e)
![image](https://github.com/kolinger/skyrc-mc3000/assets/78184229/5b350abd-1518-40ad-9c6a-295d8de1c4c4)

Else excellent application with much potential. Hope in the future you combine both applications, and that they work over same connection, and make it profiles can be preconfigured before charging (I'm charging / testing different cells all the time and don't use fixed preassigned programs...). 

Also would be nice to include charging / discharging graphs and while doing so to record capacity at discharge and charge with an option to measure and record internal resistance at this points also. Now the charger only measures internal resistance when  the program is run and then the charge level can be random. Resistance values after cell full and after cell fully discharged differ. Again hope you have the energy to continue as your project its exactly what this charger needs as the vendor software is to limited and does not show internal resistance.

**Comment by kolinger** [comment]
This is expected since Bluetooth interface of MC3000 seems unfortunately limited in scope and thus it's impossible to do the same as it's possible via USB. Specifically there is no known way to read out current profile over BLE yet it's possible over USB. Thus import from charger functionality requires USB. BLE can do only export to charger. This seems like firmware limitation as of now so there isn't much I can do about it.

This is why this application is split in two and each uses different connection - this is not ideal but originally this application wasn't mean to do import/export and I wanted to do import/export via BLE but it's not possible thus why the split and two different connections exist - to make it work at least somehow. This state isn't ideal but this comes from the fact that MC3000 is as good charger as it has bad application support - not only the apps from manufacturer are lacking but the interface BLE of MC3000 is limited as well.

I plan to implement more readable detail of profile and other minor tweaks like ability to Start stored program in similar way how Set works. I didn't plan to merge monitoring app to the profiles app since this would force me to use USB and I use MC3000 via BLE exclusively. I plug USB only when I want to do import/export and that's not as often.

My usage is obviously different to yours since I always use stored programs - I have like 10 programs that I use over and over - thus for me import/export is used to modify stored programs and then I use charger on it's own and only use BLE to monitor status remotely. This works well for me.

Logging would be nice indeed! Although that's like another project on it's own! There are other projects that cover this extensively and I can't do as much as they do (like DataExplorer) I could make some simple logging but even that is no small amount of work and I lack motivation for this since 1) other projects exist and can do more 2) there is the BLE vs USB limitation that doesn't allow me to implement the BLE app I would like and forces me to use USB that I don't want.

**Comment by AndrejValand** [comment]
Of i fully understand, it was just not clear from the project descriptions. Thanks for the feedback. I still hope you add some functionality to the BLE part of your program like manual preset of program / start stop from BLE app this should be possible as it can be done via their app but i fully understand you designed the app for you use case. So its only a wish on my side :)

**Comment by kolinger** [comment]
I updated wording a bit so now it should be clear what interface is being used for what.

Yes uploading programs via BLE is possible but there is no download and that's deal breaker for me since I want to manage my profiles on charger itself where all possible combinations of settings are presented and then saved them to PC and push them back if required. Thus only being able to push can't replace what Profiles does now.

I guess there could be some combination and use BLE for what it can be used for and also allow to use USB for what it can't be used for. That would be better compromise but that would be even more complex since all operations would be doubled and it's not easy to do. That would be best I guess but MC3000 model is quite old - 8 years? So is hard to justify major time investment for something where future is unclear. I would expected that MC3000 would have upgrade many years ago... Doubt I would find free time for something that has this kind of motivation.
