### ISSUE TITLE
Profile executable not part of the release

### ISSUE THREAD

**Issue by abbot123** [kolinger/skyrc-mc3000#5]
Hi Kolinger, thank you for this application, its very useful! I just downloaded the latest alpha release 2.2.0 but this does not have the profiles executable. Could you please release a new version with a complied version of profiles?

Thanks

**Comment by kolinger** [comment]
The profiles are part of the same executable. Installation creates two shortcuts:

MC3000 BLE
and
MC3000 USB Profiles

They share same executable `mc3000ble.exe`, the executable decided what to launch by first argument and the "profiles" launches the USB Profiles otherwise the BLE monitor application is started.

This may be confusing a bit but it was the quickest way how to add USB Profiles support to already existing BLE Status application.

I did update the readme to inform about this.

**Comment by abbot123** [comment]
Thank I see the difference now and was able to start and load the profiles over the USB cable. Is there any export or template JSON I can use to build new profiles?

**Comment by abbot123** [comment]
Okay, I seem to have found a way. This is only an issue if you have a brand new charger which has no saved profiles. 

When you load the profiles you only see the default profiles on each slot.

![image](https://github.com/user-attachments/assets/94a8d94a-6597-401a-89d4-3ac0a13a02e1)

You then need to give the profile in the first slot a name, eg "TEST" and then click the save checkbox and finally hit confirm.

![image](https://github.com/user-attachments/assets/2ca4f8fa-dbb7-4923-aac6-4b39968aba63)

After this you will see the saved profiles or if you reload the "current profiles from the charger" you see the slot profiles and the saved profiles.

![image](https://github.com/user-attachments/assets/82426ec9-33b4-446a-a401-041b580b94c6)


You can now export the test profile, modify it and import it back in again. Here is a sample json profile:

`{
 "slot_number": 0,
 "busy_tag": 0,
 "battery_type": 0,
 "operation_mode": 0,
 "capacity": 0,
 "charge_current": 1000,
 "discharge_current": 500,
 "discharge_cut_voltage": 3300,
 "charge_end_voltage": 4200,
 "charge_end_current": 100,
 "discharge_reduce_current": 500,
 "number_cycle": 1,
 "charge_resting_time": 0,
 "cycle_mode": 0,
 "peak_sense_voltage": 3,
 "trickle_current": 3,
 "restart_voltage": 0,
 "cut_temperature": 45,
 "cut_time": 180,
 "temperature_unit": 0,
 "trickle_time": 0,
 "discharge_resting_time": 0,
 "id": "6f0590f9-8779-4049-8730-bae85e4a55c0",
 "name": "TEST"
}`

**Comment by kolinger** [comment]
> Is there any export or template JSON I can use to build new profiles?

No and that's on purpose.

I strongly recommend to only configure the profiles via the charger itself, where the options are restricted and validated via the charger interface and then export such profiles and only then do minor changes if well known values via the JSON.

This application doesn't do any validation of the values thus it's not recommended to write your own profiles by hand unless you absolutely know how the charger works internally (that's impossible to know since the firmware isn't open, it's basically black box). You can easily generate invalid values or invalid combination of valid values that would lead into unexpected results.

I have no idea what validations the charger does or how robust the validation is and there is always possibility that there is no validation or the validation is too naïve and this can lead even to damage (both of the charger and battery cells).

There are lot of options, lot of modes, lot of dependencies, thus I don't currently plan to re-create the configuration interface and/or validation since that's a lot of work and also responsibility. The charger interface isn't great but it's okay if you need to use it only to create the profile and then you can manage the profile or its derivatives via the JSON.

---

BTW: There is no known way to import or export **saved** profiles from the charger. Thus everything you do works with the current slots. Thus you can import/set only current slot 1-4 and then you can save it into the charger via the charger itself, you can also recall saved profile via the charger and then you can import it via USB but you always work with current settings of the slots (1 2 3 4).

What this application does isn't really what the USB interface was meant to do since the official apps don't support the export/import of profiles. That's why the interaction between this app and the charger is limited/weird.
